### ISSUE TITLE
Add Zerilli: Even-Parity Homogeneous Solutions

### ISSUE THREAD

**Issue by thompsonphys** [BlackHolePerturbationToolkit/ReggeWheeler#4]
The `ReggeWheeler` package currently computes the homogeneous master function solutions to the ReggeWheeler equation using two different methods. These homogeneous solutions are related to the (spin 2) even-parity Zerilli master function via a simple differential relation in vacuum, which should be straightforward to implement.

Any thoughts?

**Comment by barrywardell** [comment]
I agree it would be good to add support for solving the Zerilli equation and/or for performing the transformation from Regge-Wheeler to Zerilli.

**Comment by thompsonphys** [comment]
Having the numerical integration method available would allow for future support of extended, non-point-particle sources where the transformation won't work. Would it be best to add in a separate mode function, e.g. `ZerilliMode`, or add it as a flag to a generic `ReggeWheeelerMode` quantity?

**Comment by barrywardell** [comment]
I agree. I haven't thought about whether it would be better to have a new function, or an option for the current one. Someone at the toolkit meeting also mentioned other potentials, so maybe we want something quite flexible to be extended.

**Comment by thompsonphys** [comment]
The difficulty with having an arbitrary potential is that the recurrence relations for the Jost functions are potential-dependent. If we could automate finding the recurrence relation given a potential, then that would be a fun addition.

**Comment by barrywardell** [comment]
Here's the transformation from RW to Zerilli (taken from Berndtson's thesis via Adrian). One way to get Zerilli solutions would be to wrap this around the existing RW code.
<img width="509" alt="image" src="https://user-images.githubusercontent.com/354095/82943416-7f1e7c00-9f91-11ea-8ef8-28587164197f.png">

**Comment by barrywardell** [comment]
Here's an example of some other relevant potentials (thanks to Amruta Sadhu for pointing these out): https://arxiv.org/pdf/hep-th/0305147.pdf

**Comment by barrywardell** [comment]
Some other potentials suggested by Alexander Gussmann:

- Eq. (149) of https://royalsocietypublishing.org/doi/pdf/10.1098/rspa.1991.0016
- Eq. (3.15) of https://inspirehep.net/literature/325359

The main difference compared to Schwarzschild is that there is an additional term of the form (E-P) in the effective potential (here E is the energy density of the star and P its pressure), in general E and P are model dependent functions but given a concrete model for the star these functions could be given explicitly.

**Comment by thompsonphys** [comment]
Taking radial derivatives of ReggeWheelerRadial functions seems to be broken in the current commit ( 412e45c), for example when I evaluate:
```
M = 1;
\[Omega] = 2`60*Sqrt[1/10^3];
RW = ReggeWheelerRadial[2, 2, \[Omega]];
RW["Up"]'[10`30]
```
then the output is something like the:

```
ReggeWheeler`MST`MST`Private`MSTRadialUp[2, 2, 0, 0, 
  0.126491106406735173279955741777308741348782205573008673074300, 
  1.99180009200929658390189729433796379169828107710527217507, 0, 
  0.0737619782539270944867116441366591511908354209780884719 + 
   0.4027867863242981214155914586068586125345480323325114329 I, {60., 
   30., 30.}][ReggeWheeler`ReggeWheelerRadial`Private`r]
```

**Comment by barrywardell** [comment]
I think I fixed this in a follow up commit. Can you pull the latest version and try again?

**Comment by thompsonphys** [comment]
@barrywardell oh yep, sorry didn't see that commit get pushed!

**Comment by thompsonphys** [comment]
Okay, I've pushed a (potentially working) numerical integration code for Zerilli. In the plot below I compare the real (blue) and imaginary (orange) numerical integration results for the "Up" BCs vs MST data (the points) evaluated from the MST ReggeWheeler function that's been transformed using the differential relations.

![zerilli](https://user-images.githubusercontent.com/43813555/83076491-90d55180-a06d-11ea-9917-333d89c238b7.png)

Initial results computed using the "by eye" metric appear favorable.

**Comment by thompsonphys** [comment]
I've gone in and done a bit more accuracy testing between the NI and MST methods to compute Zerilli, and the results looks pretty good (or as expected). With a precision of 25 digits set on ![\omega](https://render.githubusercontent.com/render/math?math=%5Comega), we get these relative error plots for the In/Up solutions computed via NI versus the analytic MST Zerilli:

![relative_error_l2](https://user-images.githubusercontent.com/43813555/84789427-223e4080-afe8-11ea-91eb-2204660c31a1.png)
![relative_error_l8](https://user-images.githubusercontent.com/43813555/84789443-25393100-afe8-11ea-8429-f02010c0cd43.png)
![relative_error_l20](https://user-images.githubusercontent.com/43813555/84789460-2a967b80-afe8-11ea-8844-569334734992.png)

These are for values ![\ell\in\[2,8,20\]](https://render.githubusercontent.com/render/math?math=%5Cell%5Cin%5B2%2C8%2C20%5D) and a fixed azimuthal index of ![m=2](https://render.githubusercontent.com/render/math?math=m%3D2) (for a cirular orbit at ![r_0=10M](https://render.githubusercontent.com/render/math?math=r_0%3D10M)). We run into the same high-frequency problem when looking at the ![\ell=20,m=20](https://render.githubusercontent.com/render/math?math=%5Cell%3D20%2Cm%3D20) case that we're seeing in the MST BC issue, so I upped the precision to 35 digits and that seemed to "fix" it:

![relative_error_l20m20](https://user-images.githubusercontent.com/43813555/84789856-9547b700-afe8-11ea-964e-9c02c2b2c270.png)

The one problem I'm having is with the infrastructure workflow as it's done currently in `ReggeWheelerRadial.m` (my hack to get it working [here](https://github.com/BlackHolePerturbationToolkit/ReggeWheeler/blob/Zerilli/Kernel/ReggeWheelerRadial.m#L450)). When this is uncommented, the analytic transformation is performed for `Zerilli` even when NI is used and we've integrated with the Zerilli potential/BCs. Since there are really three possible ways to get Zerilli--NI with Zerilli potential, NI with RW potential and transform, MST and transform--we may need a better solution that just a switch on `Zerilli` here.

**Comment by barrywardell** [comment]
This looks exactly as expected. The default AccuracyGoal and PrecisionGoal is WorkingPrecision/2 and the default WorkingPrecision is the precision of omega. I agree that it's not clear that the current way of doing things is right given that there are two possible ways to achieve the same thing.

**Comment by thompsonphys** [comment]
Thinking about it a bit, I think it seems reasonable to assume that if someone wants to do numerical integration with the potential set to `Zerilli`, then they will expect the full NI done in that way. So we can eliminate the third option of "do NI with RW potential and use transformations" as a built-in choice, and if someone really wants that way of getting the solution then they can write the extra bit of code themselves.
