### ISSUE TITLE
ReggeWheelerPointParticleMode produces wrong results for even sector

### ISSUE THREAD

**Issue by barrywardell** [BlackHolePerturbationToolkit/ReggeWheeler#8]
For the even sector it appears that the inhomogeneous Regge-Wheeler (CPM) master function is solved for, but the source is for the Zerilli master function. This could be fixed by using the Zerilli homogeneous solutions in place of Regge-Wheeler.

**Comment by thompsonphys** [comment]
Should be a simple fix, and I can take a look this afternoon.

**Comment by thompsonphys** [comment]
It seems that this was all written before we had the Zerilli implementation working, so the `ConvolvePointParticleSourceCircular` function in ConvolveSource.m assumes the input homogeneous solution is always for odd parity and performs the Detweiler-Chandrasekhar transformation before computing the jumps when `EvenQ[l+m]`.

The simplest fix is to rip out most of the code and then ensure upstream that the correct source and homogeneous functions are being passed into this function:

```
ConvolvePointParticleSourceCircular[(-2|2),RF_,SO_]:=
	Module[{r0,PsiIn,dPsiIn,PsiUp,dPsiUp,Wronskian,deltadPsidr,deltaPsi,ZIn,ZUp},

		r0=SO["r0"];

		PsiIn=RF["In"][r0];
		dPsiIn=RF["In"]'[r0];
		PsiUp=RF["Up"][r0];
		dPsiUp=RF["Up"]'[r0];
		
		Wronskian = PsiIn*dPsiUp - PsiUp*dPsiIn;
		deltaPsi=SO["deltaPsi"];
		deltadPsidr=SO["deltadPsidr"];
		ZIn = (PsiUp*deltadPsidr - deltaPsi*dPsiUp)/Wronskian;
		ZUp = (PsiIn*deltadPsidr - deltaPsi*dPsiIn)/Wronskian;
		<|"\[ScriptCapitalI]" -> ZUp, "\[ScriptCapitalH]" -> ZIn|>
];
```

**Comment by thompsonphys** [comment]
I've also made the change to the function calling the homogeneous solution in `ReggeWheelerPointParticleMode`:

```
radialopts = Sequence@@FilterRules[{opts}, Options[ReggeWheelerRadial]]; (*May need to remove the "Potential" option if it's in this list!*)
If[EvenQ[l+m], (*Switch for parity of the homogeneous solution*)
      R = ReggeWheelerRadial[s, l, \[Omega], "Potential"->"Zerilli", radialopts];
  ,
      R = ReggeWheelerRadial[s, l, \[Omega], "Potential"->"ReggeWheeler", radialopts];
];
 ```
I _think_ this should now allow for the `Method` to be passed in (e.g. MST) by specifying it in optional parameters, though I'm still unfamiliar with the exact Mathematica syntax to be sure.

**Comment by barrywardell** [comment]
This looks like a good fix. The only issue is that the commit appears to change all lines so it's hard to see what has changed. Can you re-commit with just the affected lines changed?

**Comment by thompsonphys** [comment]
I _think_ it's been fixed now.

**Comment by barrywardell** [comment]
This has now been merged
