### ISSUE TITLE
ReggeWheelerRadial Issue With Negative Frequencies 

### ISSUE THREAD

**Issue by joshbmat** [BlackHolePerturbationToolkit/ReggeWheeler#9]
`ReggeWheelerRadial[2, 2, -2 N[Sqrt[1/10^3], 50], 
  "Potential" -> "Zerilli", 
  Method -> {"NumericalIntegration", "Domain" -> {10, 10^4}}, 
  "BoundaryConditions" -> "Up"][10]`

gives a couple of warnings, the first of which is:

`NDSolveValue::ndsz: At ReggeWheelerNumericalIntegrationPrivatex$3285 == -1.5000000000000000000000000000000000000000015223891, step size is effectively zero; singularity or stiff system suspected.`

and returns 

`None[10]`

While

`ReggeWheelerRadial[2, 2, -N[Sqrt[1/10^3], 50], 
  "Potential" -> "ReggeWheeler", 
  Method -> {"NumericalIntegration", "Domain" -> {10, 10^4}}, 
  "BoundaryConditions" -> "Up"][10]`

seemingly runs indefinitely. 

I can just sum positive m-modes, double my answer and discard the imaginary bit but thought I'd flag this. Is this happening at the boundary conditions or something? Getting rid of the negative sign in the frequency argument runs fine.

I'm running on the latest master branch.

**Comment by thompsonphys** [comment]
The Zerilli integration error seems like it's gotten past the BC loops, so those are at least finishing (but may not be correct). The `ReggeWheelerUpBC` initializes the outer boundary to be the specific value of `r0ut=100\[omega]^(-1)`, which will be negative when evaluated with a negative frequency, so that's probably causing the convergence issue there.

I'll open a branch to start experimenting with this.

**Comment by barrywardell** [comment]
Given that the Regge-Wheeler equation only depends on $\omega^2$, maybe the most straightforward thing would be to always just return the positive frequency solutions?

**Comment by thompsonphys** [comment]
So taking Abs of the frequency when finding the starting point `rout` for the outer BC loop appears to have fixed the issue, and the result seems to agree with the MST method. @joshbmat if you'd like to pull the branch and double check?

**Comment by joshbmat** [comment]
Weirdly I'm still getting the same issue though I checked the ".m" file locally on my machine and the abs() is now there for rout

**Comment by joshbmat** [comment]
Now it's working. The old version of the package was hiding as a Mathematica paclet on my machine.

**Comment by barrywardell** [comment]
This looks like the right fix to me. The only issue with @thompsonphys's commit is that is appears to have changed all lines in the file. It would be better to replace it with a commit that only changes the affected line.

@joshbmat: you can see how to force the use of the non-paclet version here: https://bhptoolkit.org/mathematica-install-dev.html

**Comment by thompsonphys** [comment]
Ugh that's annoying. Is there a way to avoid this in general when committing Mathematica notebooks, or do I just need to be very particular with whitespace for these? I'll roll back the changes and re-commit without all the unnecessary changes.

**Comment by thompsonphys** [comment]
Should be cleaned up!

**Comment by barrywardell** [comment]
Normally it's not a problem with .m files but maybe it's a line ending (unix vs windows) issue?

**Comment by barrywardell** [comment]
This has now been merged.
